version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
      - "443:443"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - ./certs:/etc/letsencrypt
    #   - ./certs-data:/data/letsencrypt
    #   - ./renew_certificates.sh:/etc/cron.daily/renew_certificates
    environment:
      - BASE_HREF=/browser/
    restart: always
    # depends_on:
    #   - certbot

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #     - ./certs-data:/data/letsencrypt
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
